name: iotlpn
description: IoTLPN (IoT Local P2P Network) is an experimental protocol for decentralized communications between IoT devices
version: 1.0.0
repository: https://github.com/taleroangel/iotlpn_dart

environment:
  sdk: ">=2.19.2 <3.0.0"

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  
dependencies:
  msgpack_dart: ^1.0.1
  pointycastle: ^3.6.2
